'use strict';
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const fmt = (n, digits=1) => Number(n).toLocaleString('zh-CN',{maximumFractionDigits:digits});
const sources = {
  concept:{title:'新质生产力的概念依据',type:'理论依据 · 2024',description:'以创新为主导，强调科技突破、生产要素的创新配置与产业转型升级。本站四条内容主线是对主题的可视化组织，不是对宏观全要素生产率的测算。',links:[['《求是》：发展新质生产力是推动高质量发展的内在要求和重要着力点','https://www.qstheory.cn/dukan/qs/2024-05/31/c_1130154174.htm']]},
  work:{title:'Generative AI at Work',type:'实证研究 · 2024 年修订版',description:'Erik Brynjolfsson、Danielle Li、Lindsey Raymond。采用 arXiv v2 的统一口径：5,172 名客服人员，每小时解决问题数平均提高 15%。研究利用 AI 助手的分期引入分析效果，个体收益存在差异。早期版本的样本量与增幅不同，本站不混用。实验室是按平均变化率进行的算术换算，不是对个人工作表现的预测。',links:[['研究摘要与修订记录（v2）','https://arxiv.org/abs/2304.11771v2']]},
  industry:{title:'全球灯塔工厂：中国制造案例',type:'案例报告 · 世界经济论坛 · 2025-01-14',description:'首钢冷轧、佛山海天、贵州轮胎、法雷奥深圳四个案例取自同一批灯塔工厂公告。数据是包含 AI、自动化、先进分析与流程优化在内的整体数字化转型成果，不能分离为 AI 的独立因果效应。公告未统一披露基准期和原始绝对量。降低百分比不等于降低百分点；案例也不代表所有工厂。',links:[['世界经济论坛完整案例公告','https://www.weforum.org/press/2025/01/global-lighthouse-network-2025-world-economic-forum-recognizes-companies-transforming-manufacturing-through-innovation/']]},
  alphafold:{title:'AlphaFold 蛋白质结构预测数据库',type:'公开科研资源 · 2022 / 2025',description:'2022 年数据库扩展到超过 2 亿个预测结构；2025 年 10 月 21 日 v6 发布说明披露超过 2.41 亿个。两者为特定版本的历史里程碑，非实时总量。“预测结构”不等于已被实验验证的结构，也不能直接换算成药物研发成功数量或效率倍数。',links:[['EMBL-EBI：数据库扩展案例','https://www.ebi.ac.uk/about/news/perspectives/alphafold-using-open-data-and-ai-to-discover-the-3d-protein-universe/'],['EMBL-EBI：v6 发布说明','https://www.ebi.ac.uk/pdbe/news/alphafold-database-release-notes']]},
  cooling:{title:'Google 数据中心冷却优化',type:'企业披露案例 · 2016',description:'Google DeepMind 报告冷却用能最多降低 40%。本站将优化前设为 100，按最大披露降幅换算为 60，属于指数示意。不能理解成所有数据中心都能达到该降幅，也不能理解成数据中心总用能降低 40%。',links:[['DeepMind 原始案例','https://deepmind.google/blog/deepmind-ai-reduces-google-data-centre-cooling-bill-by-40/']]},
  energy:{title:'Energy and AI：数据中心用电',type:'历史估计 / 情景预测 · IEA 2025',description:'2024 年全球数据中心用电估计约 415 TWh；2030 年约 945 TWh 是 IEA 2025 年报告中的基准情景预测，非实际观测，也非最新预测的声明。统计包含 AI 和其他数字服务，不能视作 AI 单独用电。TWh 为太瓦时，1 TWh = 10 亿千瓦时。',links:[['IEA：报告执行摘要','https://www.iea.org/reports/energy-and-ai/executive-summary']]}
};
const cases = [
  {name:'首钢冷轧',full:'北京首钢冷轧',city:'北京',sector:'钢铁 / 高端汽车板',lat:39.9,lon:116.4,lead:'更严格的质量标准，更精准的生产流程。',description:'面对高端汽车制造要求和更多产品规格，工厂部署 67 项数字化应用，其中 61% 使用 AI。',metrics:[['产线效率提高',21.2,'+'],['产品缺陷减少',35,'−'],['客户投诉减少',55,'−'],['高端产品销售增长',36,'+']],flow:['生产过程数据','AI 与流程优化','精度与质量改善'],quality:35,qualityLabel:'产品缺陷减少',efficiency:21.2,efficiencyLabel:'产线效率提高'},
  {name:'佛山海天',full:'佛山海天味业',city:'佛山',sector:'食品 / 酱油生产',lat:23.0,lon:113.1,lead:'小批量、多品种，也能减少浪费。',description:'面对更多规格与小批量订单，工厂部署 50 多项数字化应用，近一半由 AI 支持。',metrics:[['原材料浪费减少',33.6,'−'],['产品缺陷率降低',39.1,'−'],['订单交付周期缩短',38.7,'−'],['小批量订单增长',64,'+']],flow:['订单与生产数据','数字化运营优化','交付与资源改善'],quality:39.1,qualityLabel:'产品缺陷率降低',efficiency:null,efficiencyLabel:'未披露同类效率指标'},
  {name:'贵州轮胎',full:'贵州轮胎',city:'贵阳',sector:'制造 / 重载轮胎',lat:26.6,lon:106.7,lead:'应对高度定制，兼顾敏捷与一致性。',description:'超过 60% 的订单具有高度定制需求。工厂引入 40 多项方案，包括 AI 辅助设计、先进分析与柔性自动化。',metrics:[['劳动生产率提高',68,'+'],['缺陷减少',57,'−'],['库存水平降低',34,'−']],flow:['定制需求与设计','AI 设计与柔性生产','生产率与质量改善'],quality:57,qualityLabel:'缺陷减少',efficiency:68,efficiencyLabel:'劳动生产率提高'},
  {name:'法雷奥深圳',full:'法雷奥深圳前视摄像头工厂',city:'深圳',sector:'汽车零部件 / 前视摄像头',lat:22.5,lon:114.1,lead:'高质量、灵活生产和更低单位能耗。',description:'工厂部署 42 项数字化应用，包括 AI 方案、生成式 AI 故障排查和自动化生产。',metrics:[['生产率提高',60.2,'+'],['成品缺陷率降低',45.9,'−'],['交付周期缩短',34.5,'−'],['单位能耗降低',27.1,'−']],flow:['生产与故障信息','AI 分析与自动化','效率与单位能耗改善'],quality:45.9,qualityLabel:'成品缺陷率降低',efficiency:60.2,efficiencyLabel:'生产率提高'}
];
const heroCases = [
  {gain:'+15%',label:'每小时解决问题数',after:115,caption:'5,172 名客服人员的研究中，AI 辅助使平均生产率提高 15%。基准指数为 100。',source:'work'},
  {gain:'−35%',label:'产品缺陷',after:65,caption:'首钢冷轧案例：包含 AI 的整体数字化改造后，产品缺陷减少 35%。基准指数为 100。',source:'industry'},
  {gain:'−33.6%',label:'原材料浪费',after:66.4,caption:'佛山海天案例：包含 AI 的整体数字化改造后，原材料浪费减少 33.6%。基准指数为 100。',source:'industry'}
];
function setActive(selector,button){$$(selector).forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',b===button?'true':'false')})}
function bars(before,after,max,unit=''){return `<div class="bar-row"><span>变化前</span><div class="bar-track"><div class="bar-fill" style="width:${before/max*100}%"></div></div><b>${fmt(before)}${unit}</b></div><div class="bar-row after"><span>变化后</span><div class="bar-track"><div class="bar-fill" style="width:${after/max*100}%"></div></div><b>${fmt(after)}${unit}</b></div>`}
function renderHero(i){const c=heroCases[i];$('#hero-chart').innerHTML=`<span class="hero-measure"><b>${c.gain}</b>${c.label}</span>${bars(100,c.after,130)}<div class="range-bounds"><span>指数 · 变化前 = 100</span><span>固定刻度 0–130</span></div>`;$('#hero-caption').textContent=c.caption;$('#hero-source').onclick=()=>showSources(c.source)}
$$('[data-hero]').forEach(b=>b.addEventListener('click',()=>{setActive('[data-hero]',b);renderHero(Number(b.dataset.hero))}));
const mechanisms=[
  {title:'把专家经验，带到更多人的工作台。',text:'AI 可以整理知识、检索信息并提供建议。劳动者保留判断与沟通职责，在协作中学习。',nodes:[['知识与经验','可复用的内容'],['AI 辅助','检索与建议'],['劳动者','判断与执行']],insight:'对应案例：客服人员的平均效率改善，且不同经验水平的收益不同。'},
  {title:'让生产工具拥有感知与辅助决策能力。',text:'从识别生产缺陷到发现设备异常，模型将生产数据转化为可用信息，与自动化和流程优化共同作用。',nodes:[['生产数据','传感与记录'],['AI 分析','识别与辅助决策'],['生产工具','执行与反馈']],insight:'对应案例：首钢冷轧提升流程精度，法雷奥采用 AI 故障排查等方案。'},
  {title:'让原本难以分析的对象，变得可探索。',text:'结构预测等能力帮助研究者形成更具体的科学假设。科学发现仍需要实验、解释和验证。',nodes:[['蛋白质序列','研究输入'],['AI 预测','结构线索'],['科学研究','假设与验证']],insight:'对应案例：AlphaFold 将大规模结构预测开放为研究资源。'},
  {title:'技术进入流程，价值才能持续发生。',text:'数据、模型、人员和生产环节需要相互配合。训练员工、改善数据和调整业务流程，都是转型的一部分。',nodes:[['数据与人才','基础条件'],['协作流程','连接与优化'],['实际价值','效率与质量']],insight:'对应案例：灯塔工厂同时采用多种数字技术，因此不能把整体收益全部归因于 AI。'}
];
function renderMechanism(i){const m=mechanisms[i];$('#mechanism-detail').innerHTML=`<h3>${m.title}</h3><p>${m.text}</p><div class="flow" aria-label="作用流程">${m.nodes.map((n,j)=>`${j?'<i aria-hidden="true">→</i>':''}<div class="${j===1?'ai-node':''}">${n[0]}<small>${n[1]}</small></div>`).join('')}</div><p class="insight">${m.insight}</p>`}
$$('[data-mech]').forEach(b=>b.addEventListener('click',()=>{setActive('[data-mech]',b);renderMechanism(Number(b.dataset.mech))}));
let selectedCase=0;
function renderLocations(){const x=lon=>35+(lon-104)/15*220,y=lat=>145-(lat-21)/21*120;$('#location-plot').innerHTML=`<svg viewBox="0 0 290 180" role="img" aria-label="四个制造案例的经纬度位置示意：北京在北，贵阳在西南，佛山与深圳位于广东"><defs><pattern id="geo-grid" width="30" height="30" patternUnits="userSpaceOnUse"><path d="M30 0H0V30" fill="none" stroke="#dbe3eb" stroke-width="1"/></pattern></defs><rect x="15" y="5" width="260" height="145" fill="url(#geo-grid)"/><text x="15" y="175" class="map-label">西 104°E</text><text x="206" y="175" class="map-label">东 119°E</text><text x="17" y="17" class="map-label">北</text>${cases.map((c,i)=>`<circle cx="${x(c.lon)}" cy="${y(c.lat)}" r="${i===selectedCase?12:7}" fill="${i===selectedCase?'#2d73c9':'#acbac8'}" fill-opacity="${i===selectedCase?.2:1}"/>${i===selectedCase?`<circle cx="${x(c.lon)}" cy="${y(c.lat)}" r="5" fill="#2d73c9"/>`:''}<text x="${x(c.lon)+(i===1?-35:12)}" y="${y(c.lat)+(i===3?17:-9)}" class="map-label">${c.city}</text>`).join('')}</svg>`}
function renderCase(i){selectedCase=i;const c=cases[i];$('#case-buttons').innerHTML=cases.map((v,j)=>`<button data-case="${j}" class="${j===i?'active':''}" aria-pressed="${j===i}">${v.name}<small>${v.city} · ${v.sector.split(' / ')[0]}</small></button>`).join('');$$('[data-case]').forEach(b=>b.onclick=()=>renderCase(Number(b.dataset.case)));$('#case-detail').innerHTML=`<div class="case-meta">${c.sector} / 2025 灯塔工厂案例</div><h3>${c.full}</h3><p>${c.lead}</p><div class="case-metrics">${c.metrics.map(m=>`<div class="case-metric"><b>${m[2]}${m[1]}<span>%</span></b><span>${m[0]}</span></div>`).join('')}</div><div class="case-process">${c.flow.map((f,j)=>`${j?'<i>→</i>':''}<span>${f}</span>`).join('')}</div><p class="fine">${c.description}</p><button class="text-button" data-source="industry">查看完整来源及统计口径 ↗</button>`;renderLocations()}
function renderComparison(kind){$('#comparison').innerHTML=cases.map(c=>{const value=c[kind];return `<div class="comparison-item"><span>${c.name}</span><b class="${value===null?'unavailable':''}">${value===null?'未披露':(kind==='quality'?'−':'+')+value+'%'}</b><small>${c[kind+'Label']}</small><div class="mini-track"><i style="width:${value===null?0:value}%;background:${kind==='quality'?'#168a79':'#377bdc'}"></i></div></div>`}).join('')}
$$('[data-compare]').forEach(b=>b.onclick=()=>{setActive('[data-compare]',b);renderComparison(b.dataset.compare)});
const scienceTexts=['蛋白质的氨基酸序列提供研究输入。开放数据与前期实验研究，为模型的开发和应用奠定基础。','AI 根据序列预测可能的三维结构，为研究提供线索。预测具有不确定性，不能当作全部已经验证的事实。','研究者结合结构线索与专业知识提出假设，例如进一步研究某个蛋白质的功能。','通过实验检验假设、修正认识。AI 预测支持这一过程，不能替代全部实验和科学判断。'];
$$('[data-science]').forEach(b=>b.onclick=()=>{setActive('[data-science]',b);$('#science-explanation').textContent=scienceTexts[Number(b.dataset.science)]});
const labConfigs={
  work:{title:'同样一小时，能处理多少问题？',description:'按客服研究中平均 15% 的生产率增幅换算。',label:'原本每小时解决的问题数',unit:'个 / 小时',min:1,max:100,step:1,value:20,presets:[10,20,50],rate:.15,source:'work',assumption:'假设工作类型、难度和工时不变，且达到研究中的平均相对增幅。输入是你设定的情景。'},
  quality:{title:'同一批产品，缺陷会怎样变化？',description:'按首钢冷轧案例中 35% 的产品缺陷降幅换算。',label:'原本一批产品中的缺陷数量',unit:'个',min:10,max:1000,step:10,value:100,presets:[50,100,500],rate:.35,source:'industry',assumption:'假设产品总量与统计口径不变，达到案例中的相对降幅。结果是理论换算值，可为小数。'},
  resource:{title:'同样的生产任务，减少多少浪费？',description:'按佛山海天案例中 33.6% 的原材料浪费降幅换算。',label:'原本原材料浪费的重量',unit:'千克',min:10,max:1000,step:10,value:100,presets:[50,100,500],rate:.336,source:'industry',assumption:'假设产出与原材料统计口径不变，达到案例中的相对降幅。千克是本实验设定的单位。'}
};
let labKind='work';
function configureLab(kind){labKind=kind;const c=labConfigs[kind];$('#lab-title').textContent=c.title;$('#lab-description').textContent=c.description;$('#input-label').textContent=c.label;$('#input-unit').textContent=c.unit;$('#range-min').textContent=c.min;$('#range-max').textContent=c.max;$('#lab-assumption').textContent=c.assumption;for(const id of ['#lab-input','#lab-range']){const el=$(id);el.min=c.min;el.max=c.max;el.step=c.step;el.value=c.value;}$('#lab-input').setAttribute('aria-invalid','false');$('.number-field').classList.remove('invalid');$('#lab-presets').innerHTML=c.presets.map(n=>`<button data-preset="${n}">${n} ${c.unit}</button>`).join('');$$('[data-preset]').forEach(b=>b.onclick=()=>{setLabValue(Number(b.dataset.preset))});$('#lab-source').onclick=()=>showSources(c.source);renderLab(c.value)}
function setLabValue(n){const c=labConfigs[labKind];n=Math.max(c.min,Math.min(c.max,n));$('#lab-input').value=n;$('#lab-range').value=n;$('#lab-input').setAttribute('aria-invalid','false');$('.number-field').classList.remove('invalid');renderLab(n)}
function renderLab(n){const c=labConfigs[labKind],isWork=labKind==='work',after=n*(isWork?1+c.rate:1-c.rate),diff=Math.abs(after-n);$('#lab-result-header').innerHTML=`<div class="result-heading"><span>换算结果 · ${isWork?'每小时处理量':labKind==='quality'?'缺陷数量':'原材料浪费'}</span><span class="tag">情景计算</span></div><div class="result-total">${fmt(after)}<small>${c.unit}</small></div><p class="result-delta">${isWork?'增加':'减少'} ${fmt(diff)} ${c.unit} · 相对变化 ${isWork?'+':'−'}${fmt(c.rate*100)}%</p>`;$('#lab-chart').innerHTML=bars(n,after,Math.max(n,after)*1.2);let extra,formula;if(isWork){const beforeH=100/n,afterH=100/after;extra=`<div><span>处理 100 个问题 · 原用时</span><b>${fmt(beforeH,2)}<small>小时</small></b></div><div><span>处理 100 个问题 · 新用时</span><b>${fmt(afterH,2)}<small>小时</small></b></div>`;formula=`新处理量 = ${fmt(n)} × 1.15 = ${fmt(after,2)} 个/小时。<br>完成固定工作量的时间 = 工作量 ÷ 每小时处理量。<br>用时降幅 = 1 − 1 / 1.15 ≈ 13.04%。<br>这只是平均增幅下的情景换算，没有估计培训成本、复核时间或个体差异。`}else{extra=`<div><span>相对于原值的剩余比例</span><b>${fmt((1-c.rate)*100)}<small>%</small></b></div><div><span>理论减少量</span><b>${fmt(diff)}<small>${c.unit}</small></b></div>`;formula=`变化后 = ${fmt(n)} × (1 − ${fmt(c.rate*100)}%) = ${fmt(after,2)}。<br>减少量 = ${fmt(n)} × ${fmt(c.rate*100)}% = ${fmt(diff,2)}。<br>${labKind==='quality'?'这里展示的是缺陷数量的相对降幅；没有总产量就不能计算缺陷率或其百分点变化。':'原材料浪费降低 33.6%，不等于全部原材料消耗降低 33.6%。'}<br>案例为整体数字化转型成果，不能据此分离 AI 的独立作用。`;}$('#lab-extra').innerHTML=`<div class="lab-extra">${extra}</div>`;$('#lab-formula').innerHTML=`<p>${formula}</p>`;}
$$('[data-lab]').forEach(b=>b.onclick=()=>{setActive('[data-lab]',b);configureLab(b.dataset.lab)});
$('#lab-range').addEventListener('input',e=>setLabValue(Number(e.target.value)));
$('#lab-input').addEventListener('input',e=>{const c=labConfigs[labKind],n=e.target.valueAsNumber,valid=Number.isFinite(n)&&n>=c.min&&n<=c.max;e.target.setAttribute('aria-invalid',!valid);$('.number-field').classList.toggle('invalid',!valid);if(valid){$('#lab-range').value=n;renderLab(n)}else{$('#lab-result-header').innerHTML=`<div class="result-heading">请输入 ${c.min}–${c.max} 范围内的数字</div>`;$('#lab-chart').innerHTML='';$('#lab-extra').innerHTML='';$('#lab-formula').textContent='输入有效数字后显示计算公式。'}});
$('#lab-input').addEventListener('change',e=>{const n=e.target.valueAsNumber;if(Number.isFinite(n))setLabValue(n)});
$('#reset-lab').onclick=()=>configureLab(labKind);
function renderEnergy(){const vals=[415,945],xs=[135,290],scale=115/1000;$('#energy-chart').innerHTML=`<svg viewBox="0 0 400 175" role="img" aria-label="全球数据中心用电：2024 年估计 415 太瓦时，2030 年基准情景预测 945 太瓦时。纵轴从零开始。"><defs><pattern id="forecast-hatch" width="7" height="7" patternUnits="userSpaceOnUse"><rect width="7" height="7" fill="#e8eef6"/><path d="M0 7L7 0" stroke="#91abc9" stroke-width="2"/></pattern></defs>${[0,500,1000].map(v=>`<line x1="50" x2="375" y1="${135-v*scale}" y2="${135-v*scale}" stroke="#e5e9ee"/><text x="40" y="${139-v*scale}" text-anchor="end" class="chart-axis">${v}</text>`).join('')}${vals.map((v,i)=>`<rect x="${xs[i]-28}" y="${135-v*scale}" width="56" height="${v*scale}" fill="${i?'url(#forecast-hatch)':'#377bdc'}" rx="3"/><text x="${xs[i]}" y="${126-v*scale}" text-anchor="middle" fill="#28476c" font-size="15">${v}</text><text x="${xs[i]}" y="157" text-anchor="middle" class="chart-axis">${i?'2030 · 预测':'2024 · 估计'}</text>`).join('')}<text x="50" y="12" class="chart-axis">TWh</text></svg>`}
function showSources(key){const entries=key?[[key,sources[key]]]:Object.entries(sources);$('#source-content').innerHTML=`<p class="evidence-note">本站区分实证研究、案例披露、历史估计与情景预测。图表中的基准指数和用户输入是解释工具；它们不作为原始观测数据。</p>${entries.map(([k,s])=>`<article class="source-entry"><span class="source-type">${s.type}</span><h3>${s.title}</h3><p>${s.description}</p>${s.links.map(l=>`<p><a href="${l[1]}" target="_blank" rel="noopener noreferrer">${l[0]} ↗</a></p>`).join('')}</article>`).join('')}${key?'<button class="text-button" id="all-sources">查看全部来源</button>':''}`;if(!$('#source-dialog').open)$('#source-dialog').showModal();$('#source-dialog').scrollTop=0;if($('#all-sources'))$('#all-sources').onclick=()=>showSources();}
document.addEventListener('click',e=>{const el=e.target.closest('[data-source],[data-sources]');if(el)showSources(el.dataset.source)});
$('#close-dialog').onclick=()=>$('#source-dialog').close();
$('#source-dialog').addEventListener('click',e=>{if(e.target===$('#source-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});
$('#download-data').onclick=()=>{const rows=[['案例','城市','指标','相对变化百分比','发布年份','来源','说明'],...cases.flatMap(c=>c.metrics.map(m=>[c.name,c.city,m[0],(m[2]==='−'?'-':'+')+m[1],2025,sources.industry.links[0][1],'含AI的整体数字化转型成果；非AI独立效应；基准期未统一披露']))];const csv='\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='智变-中国制造案例数据.csv';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)};
const menuToggle=$('#menu-toggle');
function closeMenu(){menuToggle.setAttribute('aria-expanded','false');$('.header').classList.remove('menu-open')}
menuToggle.onclick=()=>{const open=menuToggle.getAttribute('aria-expanded')!=='true';menuToggle.setAttribute('aria-expanded',String(open));$('.header').classList.toggle('menu-open',open)};
$$('.header nav a,.header .brand,.header [data-sources]').forEach(a=>a.addEventListener('click',closeMenu));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menuToggle.getAttribute('aria-expanded')==='true'){closeMenu();menuToggle.focus()}});
document.addEventListener('click',e=>{if(!e.target.closest('.header'))closeMenu()});
window.matchMedia('(min-width: 981px)').addEventListener('change',closeMenu);
const navLinks=$$('.header nav a');
const navSections=navLinks.map(a=>$(a.getAttribute('href')));
let navPending=false;
function updateChapter(){let current=0;navSections.forEach((s,i)=>{if(s.getBoundingClientRect().top<=window.innerHeight*.3)current=i});navLinks.forEach((a,i)=>{a.classList.toggle('current',i===current);if(i===current)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')});navPending=false}
window.addEventListener('scroll',()=>{if(!navPending){navPending=true;requestAnimationFrame(updateChapter)}},{passive:true});
window.addEventListener('resize',updateChapter);window.addEventListener('load',updateChapter);updateChapter();

renderHero(0);renderMechanism(0);renderCase(0);renderComparison('quality');$('#science-explanation').textContent=scienceTexts[0];configureLab('work');renderEnergy();
