'use strict';
(() => {
const industryHost=document.querySelector('#industry .wrap');
const compare=document.createElement('div');compare.className='pair-module';compare.id='case-compare';
compare.innerHTML=`<div class="enh-heading"><div><span class="eyebrow muted">CASE COMPARISON / 双案例探索</span><h3>同一种技术，不同的价值路径。</h3></div><p>选择两个生产现场，比较问题、应用环节与已披露成果。</p></div><div class="pair-selectors"><label>案例 A<select id="pair-a" aria-label="选择案例 A"></select></label><button id="swap-pair" aria-label="交换两个案例">交换案例</button><label>案例 B<select id="pair-b" aria-label="选择案例 B"></select></label></div><div class="pair-tabs" role="group" aria-label="案例对比维度"><button data-pair-tab="path" class="active" aria-pressed="true">问题与应用</button><button data-pair-tab="quality" aria-pressed="false">质量变化</button><button data-pair-tab="resource" aria-pressed="false">资源与交付</button></div><div id="pair-results" aria-live="polite"></div><div class="pair-note"><strong>看路径，也看口径。</strong><span>案例为整体数字化转型成果。基准期、产品和测量方式不同，降幅不能用于评价哪家工厂“更先进”。</span><button class="text-button" data-source="industry">查阅来源 ↗</button></div>`;
industryHost.append(compare);
const pairLabels=[['原材料浪费减少',33.6],['库存水平降低',34],['单位能耗降低',27.1]];
const resources=[[],[['原材料浪费减少',33.6],['订单交付周期缩短',38.7]],[['库存水平降低',34]],[['单位能耗降低',27.1],['交付周期缩短',34.5]]];
['#pair-a','#pair-b'].forEach((s,i)=>{$(s).innerHTML=cases.map((c,j)=>`<option value="${j}">${c.name} · ${c.city}</option>`).join('');$(s).value=i?3:0;$(s).onchange=renderPair});
let pairTab='path';
function renderPair(){const a=Number($('#pair-a').value),b=Number($('#pair-b').value);$('#pair-results').innerHTML=`${a===b?'<p class="same-case-note">你选择了同一案例；可更换一侧探索不同生产场景。</p>':''}<div class="pair-columns">${[a,b].map((index,i)=>{const c=cases[index];let content='';if(pairTab==='path'){content=`<h5>生产难题</h5><p>${c.lead}</p><h5>应用方式</h5><p>${c.description}</p><div class="pair-flow">${c.flow.map((v,j)=>`<span><em>${j+1}</em>${v}</span>`).join('')}</div>`}else if(pairTab==='quality'){content=`<h5>${c.qualityLabel}</h5><div class="pair-big">−${c.quality}%</div><div class="indexed-row"><span>改造前</span><div><i style="width:100%"></i></div><b>100</b></div><div class="indexed-row"><span>改造后</span><div><i style="width:${100-c.quality}%"></i></div><b>${fmt(100-c.quality)}</b></div><p class="fine">各自改造前设为 100；为相对变化的指数示意。原始绝对量及统一基准期未披露。${c.qualityLabel.includes('率')?'本案例指标是缺陷率的相对降幅。':'本案例表述为缺陷减少，未据此推算缺陷率。'}</p>`}else{content=resources[index].length?resources[index].map(m=>`<div class="resource-row"><span>${m[0]}</span><b>−${m[1]}%</b></div>`).join(''):'<p class="missing-metric">该公告未披露本案例的资源或交付同类指标。</p>';content+='<p class="fine">保留各指标原名称。库存、单位能耗和交付周期分别展示，不合成评分。</p>'}return `<article class="pair-card"><span class="pair-letter">${i?'B':'A'} / ${c.sector}</span><h4>${c.full}</h4>${content}</article>`}).join('')}</div>`;}
$$('[data-pair-tab]').forEach(b=>b.onclick=()=>{setActive('[data-pair-tab]',b);pairTab=b.dataset.pairTab;renderPair()});$('#swap-pair').onclick=()=>{const a=$('#pair-a').value;$('#pair-a').value=$('#pair-b').value;$('#pair-b').value=a;renderPair()};renderPair();

const sim=document.createElement('div');sim.id='production-sim';sim.className='production-sim';
sim.innerHTML=`<div class="enh-heading"><div><span class="eyebrow">SYSTEM EXPERIMENT / 多因素生产模拟</span><h3>局部变快，整体一定变快吗？</h3></div><p>调整加工、质检和返工条件，观察系统瓶颈。<br>教学模型 · 不代表真实企业或 AI 收益预测。</p></div><div class="sim-presets" role="group" aria-label="生产模拟预设"><button data-sim-preset="base">起点：基础生产线</button><button data-sim-preset="speed">只提高加工速度</button><button data-sim-preset="balanced">质量与流程协同</button></div><div class="sim-layout"><div class="sim-controls"><div id="sim-sliders"></div><button id="pin-baseline" class="button outline">将当前参数设为对照</button><button id="reset-sim" class="text-button">恢复初始实验</button><p class="fine">预设是人为设置的教学情景。它们体现不同改进路径，不对应特定工厂。</p></div><div class="sim-output"><div class="bottleneck-label">当前瓶颈 <strong id="bottleneck"></strong><span id="sim-clock">累计 8.0 小时</span></div><div class="production-flow" id="production-flow"></div><div class="flow-legend"><span>主流程：加工 → 质检 → 合格产出</span><span>缺陷品仅返工一次，80% 修复成功；返工共用加工资源。</span></div><div class="sim-results" id="sim-results" aria-live="polite"></div><div class="sim-playback"><button id="sim-play" class="button lime" aria-pressed="false">播放 8 小时过程</button><label for="sim-time">累计时间</label><input type="range" id="sim-time" min="0" max="8" step="0.1" value="8"><output for="sim-time" id="sim-time-value">8.0 h</output></div><div class="sim-breakdown" id="sim-breakdown"></div></div></div><div class="sim-lower"><div><h4>继续提速，收益在哪里变平？</h4><p>仅改变加工速度，其他参数保持当前值。</p><div id="sensitivity-chart"></div></div><div class="sim-insight"><span class="eyebrow">WHAT CHANGED</span><h4 id="sim-insight-title"></h4><p id="sim-insight-copy"></p><div id="baseline-summary"></div></div></div><details class="sim-method"><summary>模型公式、假设与解释范围</summary><p>稳态连续流模型：加工速度 p（件/小时）、质检速度 q（件/小时）、初检缺陷比例 d、单件缺陷返工时间 r（分钟）。原料充足，所有缺陷品均返工一次，返工成功率固定 80%，修复后直接进入合格品；无二次质检。返工消耗同一加工资源，质检只统计初检。</p><p>有效加工能力 C = 60 ÷ (60/p + d×r)；进入初检的流量 F = min(C,q)；合格品流量 G = F×(1−0.2d)。运行 t 小时的初检量为 Ft，直接合格 Ft(1−d)，返工量 Ftd，修复量 0.8Ftd，报废量 0.2Ftd。</p><p>1000 件合格订单用时 = 1000/G，仅为稳态折算，不包含启动、排队、停机、批次切换和最后一件产品的流转时间。动画按稳态流量累积期望值，不逐件模拟排队。小数表示期望数量。模型不计成本、能源和实施周期，不能据此计算企业投资回报或 AI 独立贡献。</p></details>`;
$('#lab .wrap').prepend(sim);
const originalHeading=$('#lab .wrap > .section-heading');if(originalHeading)originalHeading.insertAdjacentHTML('beforebegin','<div class="arithmetic-divider"><span>CASE ARITHMETIC / 继续探索真实案例的比例换算</span></div>');
const defaults={speed:100,inspection:80,defect:10,rework:3};let state={...defaults},baseline={...defaults},time=8,playing=false,frameId=0,startTime=0,startHours=0;
const controls=[['speed','加工速度',60,300,10,'件/小时'],['inspection','质检速度',40,200,10,'件/小时'],['defect','初检缺陷比例',0,30,1,'%'],['rework','单件缺陷返工时间',0,8,.5,'分钟']];
$('#sim-sliders').innerHTML=controls.map(([key,label,min,max,step,unit])=>`<label for="sim-${key}">${label}<output id="value-${key}">${state[key]} ${unit}</output></label><input type="range" id="sim-${key}" min="${min}" max="${max}" step="${step}" value="${state[key]}">`).join('');
function readModel(s=state,t=time){return productionModel.calculate(s,t)}
function stop(){playing=false;cancelAnimationFrame(frameId);$('#sim-play').textContent=time>=8?'重新播放':'继续播放';$('#sim-play').setAttribute('aria-pressed','false');}
function updateControls(){controls.forEach(([k,l,min,max,step,u])=>{$('#sim-'+k).value=state[k];$('#value-'+k).textContent=state[k]+' '+u});}
controls.forEach(([key,l,min,max,step,unit])=>$('#sim-'+key).oninput=e=>{stop();state[key]=Number(e.target.value);updateControls();renderSim()});
const presets={base:defaults,speed:{...defaults,speed:240},balanced:{speed:180,inspection:140,defect:4,rework:1}};
$$('[data-sim-preset]').forEach(b=>b.onclick=()=>{stop();state={...presets[b.dataset.simPreset]};time=8;updateControls();renderSim()});
$('#pin-baseline').onclick=()=>{baseline={...state};renderSim()};$('#reset-sim').onclick=()=>{stop();state={...defaults};baseline={...defaults};time=8;updateControls();renderSim()};
$('#sim-time').oninput=e=>{stop();time=Number(e.target.value);renderSim(false)};
$('#sim-play').onclick=()=>{if(playing){stop();return}if(time>=8)time=0;playing=true;startTime=performance.now();startHours=time;$('#sim-play').textContent='暂停';$('#sim-play').setAttribute('aria-pressed','true');function tick(now){time=Math.min(8,startHours+(now-startTime)/2000);renderSim(false);if(time<8&&playing)frameId=requestAnimationFrame(tick);else stop()}frameId=requestAnimationFrame(tick)};
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});
function renderSim(full=true){const m=readModel(),b=readModel(baseline,8);$('#sim-clock').textContent=`累计 ${time.toFixed(1)} 小时`;$('#sim-time').value=time;$('#sim-time-value').textContent=time.toFixed(1)+' h';$('#bottleneck').textContent=m.bottleneck;
$('#production-flow').innerHTML=`<div class="flow-station ${m.bottleneck==='加工与返工'?'is-bottleneck':''}"><span>01 加工与返工</span><b>${fmt(m.processing)}</b><small>有效能力 · 件/小时</small><div class="capacity-meter"><i style="width:${m.processingUse*100}%"></i></div><em>资源使用 ${fmt(m.processingUse*100)}%</em></div><span class="flow-connector" aria-hidden="true">→</span><div class="flow-station ${m.bottleneck==='质检'?'is-bottleneck':''}"><span>02 质检</span><b>${state.inspection}</b><small>检查能力 · 件/小时</small><div class="capacity-meter"><i style="width:${m.inspectionUse*100}%"></i></div><em>资源使用 ${fmt(m.inspectionUse*100)}%</em></div><span class="flow-connector" aria-hidden="true">→</span><div class="flow-station good-station"><span>03 合格产出</span><b>${fmt(m.good)}</b><small>${time.toFixed(1)} 小时累计期望件数</small><em>合格流量 ${fmt(m.goodRate)} 件/小时</em></div>`;
const delta=(m.goodRate/b.goodRate-1)*100;$('#sim-results').innerHTML=`<div><span>合格品流量</span><b>${fmt(m.goodRate)}<small>件/小时</small></b></div><div><span>相对对照流量</span><b>${delta>=0?'+':''}${fmt(delta)}<small>%</small></b></div><div><span>1000 件合格订单</span><b>${fmt(m.orderHours,2)}<small>小时 · 稳态折算</small></b></div>`;
$('#sim-breakdown').innerHTML=`<div><span>直接合格</span><b>${fmt(m.firstPass)} 件</b></div><div><span>进入返工</span><b>${fmt(m.reworked)} 件</b></div><div><span>返工修复</span><b>${fmt(m.recovered)} 件</b></div><div><span>最终报废</span><b>${fmt(m.scrapped)} 件</b></div>`;
if(full){$('#sim-insight-title').textContent=m.bottleneck==='质检'?'质检已成为限制产出的环节。':m.bottleneck==='加工与返工'?'加工与返工正在共用有限产能。':'两个环节的能力接近均衡。';$('#sim-insight-copy').textContent=m.bottleneck==='质检'?`当前有效加工能力为 ${fmt(m.processing)} 件/小时，高于质检的 ${state.inspection} 件/小时。继续单独提高加工速度，合格产出会停在平台区；可尝试提高质检速度。`:`返工将加工能力从名义 ${state.speed} 件/小时折算为 ${fmt(m.processing)} 件/小时。降低缺陷或缩短返工时间，可以释放加工资源；也要观察质检能否承接。`;$('#baseline-summary').innerHTML=`<span>当前对照</span><p>加工 ${baseline.speed} · 质检 ${baseline.inspection} 件/小时<br>缺陷 ${baseline.defect}% · 返工 ${baseline.rework} 分钟/件<br>合格流量 ${fmt(b.goodRate)} 件/小时</p>`;renderCurve(m);}}
function renderCurve(m){const points=[];for(let p=60;p<=300;p+=10)points.push([p,readModel({...state,speed:p},8).goodRate]);const max=Math.ceil(Math.max(...points.map(v=>v[1]),1)/20)*20;const x=p=>55+(p-60)/240*430,y=v=>175-v/max*140;$('#sensitivity-chart').innerHTML=`<svg viewBox="0 0 520 225" role="img" aria-label="加工速度敏感性曲线：横轴加工速度60到300件每小时，纵轴合格品流量，质检成为瓶颈后曲线出现平台"><text x="55" y="17" class="sim-axis">合格品流量 · 件/小时</text>${[0,max/2,max].map(v=>`<line x1="55" x2="485" y1="${y(v)}" y2="${y(v)}" stroke="#3a4c62"/><text x="45" y="${y(v)+4}" text-anchor="end" class="sim-axis">${fmt(v)}</text>`).join('')}<polyline points="${points.map(([p,v])=>`${x(p)},${y(v)}`).join(' ')}" fill="none" stroke="#d8f679" stroke-width="3"/><line x1="${x(state.speed)}" x2="${x(state.speed)}" y1="${y(m.goodRate)}" y2="175" stroke="#9cacbf" stroke-dasharray="4 4"/><circle cx="${x(state.speed)}" cy="${y(m.goodRate)}" r="6" fill="#d8f679" stroke="#152538" stroke-width="2"/>${[60,120,180,240,300].map(p=>`<text x="${x(p)}" y="198" text-anchor="middle" class="sim-axis">${p}</text>`).join('')}<text x="270" y="220" text-anchor="middle" class="sim-axis">加工速度 · 件/小时</text></svg>`}
renderSim();
})();
