'use strict';
(() => {
const colors={before:'#a6b6c6',good:'#188879',lime:'#d8f679',science:'#8060cc',rework:'#e8ad62',loss:'#e17b88'};
const svg=(body,view,label)=>`<svg class="viz-chart viz-enter" viewBox="${view}" role="img" aria-label="${label}"><title>${label}</title>${body}</svg>`;
const legend=(a,b,col=colors.good)=>`<div class="viz-legend"><span><i style="background:${colors.before}"></i>${a}</span><span><i style="background:${col}"></i>${b}</span></div>`;
function columns(values,labels,{max=130,color=colors.good,unit='指数',suffix=['',''],title='前后对比'}={}){
 const y=v=>185-v/max*140;
 return svg(`<text x="48" y="20" class="viz-small">${unit} · 纵轴从 0 开始</text>${[0,max/2,max].map(v=>`<line x1="48" x2="360" y1="${y(v)}" y2="${y(v)}" class="viz-grid"/><text x="38" y="${y(v)+4}" text-anchor="end" class="viz-axis">${fmt(v)}</text>`).join('')}${values.map((v,i)=>`<rect x="${102+i*144}" y="${y(v)}" width="66" height="${185-y(v)}" rx="4" fill="${i?color:colors.before}"/><text x="${135+i*144}" y="${y(v)-12}" text-anchor="middle" class="viz-value">${fmt(v,2)}${suffix[i]}</text><text x="${135+i*144}" y="210" text-anchor="middle" class="viz-axis">${labels[i]}</text>`).join('')}`,'0 0 410 230',`${title}：${labels[0]} ${values[0]}${suffix[0]}，${labels[1]} ${values[1]}${suffix[1]}，单位${unit}`);
}
const oldHero=renderHero;
renderHero=function(i){oldHero(i);const c=heroCases[i];$('#hero-chart').innerHTML=`<span class="hero-measure"><b>${c.gain}</b>${c.label}</span>${columns([100,c.after],['变化前','变化后'],{color:colors.lime,title:c.label})}<p class="viz-note">变化前 = 100 · 三个主题使用相同刻度</p>`};renderHero(Number($('.hero-tabs .active').dataset.hero));
function metricRow(m){const after=100+(m[2]==='+'?m[1]:-m[1]),x=v=>12+v/180*250;return `<div class="metric-visual-row"><div><span>${m[0]}</span><b>${m[2]}${m[1]}%</b></div>${svg(`<line x1="12" x2="262" y1="56" y2="56" class="viz-grid"/><line x1="${x(100)}" x2="${x(100)}" y1="3" y2="53" stroke="#91a6bb" stroke-dasharray="3 3"/><rect x="12" y="5" width="${x(100)-12}" height="16" rx="3" fill="${colors.before}"/><rect x="12" y="29" width="${x(after)-12}" height="16" rx="3" fill="${colors.good}"/><text x="${x(100)+6}" y="18" class="viz-small">100</text><text x="${x(after)+6}" y="42" class="viz-small">${fmt(after)}</text><text x="12" y="72" class="viz-small">0</text><text x="262" y="72" text-anchor="end" class="viz-small">180</text>`,'0 0 305 78',`${m[0]} ${m[2]}${m[1]}%，改造前指数100，改造后${after}`)}</div>`}
const oldCase=renderCase;
renderCase=function(i){oldCase(i);$('.case-metrics').innerHTML=legend('改造前 = 100','改造后')+cases[i].metrics.map(metricRow).join('')+'<p class="metric-caption">各指标分别归一为 100，刻度统一为 0–180；不表示指标原始数量或共同单位。</p>'};renderCase(selectedCase);
renderComparison=function(kind){const max=kind==='quality'?100:180,x=v=>210+v/max*390;$('#comparison').innerHTML=`<p class="comparison-heading-note">${kind==='quality'?'哑铃图 / 看清各自的缺陷变化':'哑铃图 / 不同口径的效率改善'} · 各自改造前 = 100</p>${legend('改造前','改造后')}<div class="viz-scroll" tabindex="0" aria-label="四家工厂前后变化图，窄屏可横向滚动">${svg(`${[0,max/2,max].map(v=>`<line x1="${x(v)}" x2="${x(v)}" y1="20" y2="293" class="viz-grid"/><text x="${x(v)}" y="315" text-anchor="middle" class="viz-axis">${fmt(v)}</text>`).join('')}${cases.map((c,i)=>{const v=c[kind],y=50+i*68,after=100+(kind==='quality'?-v:v);return `<text x="5" y="${y-3}" class="viz-value">${c.name}</text><text x="5" y="${y+18}" class="viz-small">${c[kind+'Label']}</text>${v===null?`<text x="310" y="${y+4}" class="viz-axis">未披露 · 不按 0 绘制</text>`:`<line x1="${x(100)}" x2="${x(after)}" y1="${y}" y2="${y}" stroke="${colors.good}" stroke-width="4"/><circle cx="${x(100)}" cy="${y}" r="6" fill="${colors.before}"/><circle cx="${x(after)}" cy="${y}" r="7" fill="${colors.good}"/><text x="${x(after)}" y="${y-14}" text-anchor="middle" class="viz-value">${fmt(after)}</text>`}`}).join('')}`,'0 0 640 330','四家工厂各自改造前后指数。口径不同，仅并列展示，不作排名。')}</div>`};renderComparison($('.segmented .active').dataset.compare);
function pairChart(){const host=$('#pair-results');if(host.querySelector('.pair-dumbbell')||!host.querySelector('.indexed-row'))return;host.querySelectorAll('.pair-card').forEach(card=>{const n=Number(card.querySelectorAll('.indexed-row b')[1].textContent.replace(/,/g,''));card.querySelectorAll('.indexed-row').forEach(r=>r.remove());card.insertAdjacentHTML('beforeend',`<div class="pair-dumbbell">${svg(`<line x1="30" y1="50" x2="${30+2.6*n}" y2="50" class="viz-grid"/><line x1="${30+2.6*n}" y1="50" x2="290" y2="50" stroke="${colors.good}" stroke-width="4"/><circle cx="290" cy="50" r="7" fill="${colors.before}"/><circle cx="${30+2.6*n}" cy="50" r="8" fill="${colors.good}"/><text x="290" y="24" text-anchor="end" class="viz-axis">改造前 100</text><text x="${30+2.6*n}" y="86" text-anchor="middle" class="viz-value">改造后 ${n}</text><text x="30" y="53" class="viz-small">0</text>`,'0 0 325 110',`改造前100，改造后${n}`)}</div>`)});}
new MutationObserver(pairChart).observe($('#pair-results'),{childList:true});pairChart();
$('.human .stat-label').insertAdjacentHTML('afterend',columns([100,115],['未使用 AI','AI 辅助'],{title:'客服平均生产率',color:colors.good})+'<p class="viz-note">基准指数 = 100 · 平均提高 15%，并非逐年趋势。</p>');
$('.science .stat-label').insertAdjacentHTML('afterend',columns([2,2.41],['2022 · 扩展','2025 · v6'],{max:3,color:colors.science,unit:'亿个预测结构',suffix:['+','+'],title:'数据库历史规模'})+'<p class="viz-note">柱高按已披露门槛值绘制，实际均超过标示值；不据此计算精确增长率。</p>');
$('.cooling-bars').insertAdjacentHTML('afterend',columns([100,60],['优化前','优化后*'],{max:100,title:'冷却用能指数'}));
$('#energy-chart').innerHTML=columns([415,945],['2024 · 估计','2030 · 预测'],{max:1000,title:'全球数据中心整体用电',unit:'TWh',color:colors.good}).replace('<title>','<defs><pattern id="viz-forecast" width="7" height="7" patternUnits="userSpaceOnUse"><rect width="7" height="7" fill="#e5edf5"/><path d="M0 7L7 0" stroke="#829fbb" stroke-width="2"/></pattern></defs><title>').replace(`fill="${colors.good}"`,'fill="url(#viz-forecast)"');
$('.hero-note').textContent='柱状对比 / 变化哑铃图 / 产出折线 / 质量构成环形图';
const simCharts=document.createElement('div');simCharts.className='sim-viz-grid';simCharts.innerHTML='<article class="viz-panel"><span class="viz-eyebrow">COMPOSITION / 结果构成</span><h4>每一份产出，最终去了哪里？</h4><div id="composition-chart"></div><p class="viz-note">三部分互斥，合计为初检总量。返工品中已修复的部分计入合格品。改变缺陷比例会改变构成；返工时间主要影响总量。</p></article><article class="viz-panel"><span class="viz-eyebrow">ACCUMULATION / 累计产出</span><h4>同样八小时，两条生产路径。</h4><div id="accumulation-chart"></div><p class="viz-note">直线来自恒定稳态流量假设，表示教学情景的期望累计值。虚线为已保存的对照参数；图中不模拟启动与排队。</p></article>';
$('.sim-lower').before(simCharts);
function drawSim(s,b,t){const m=productionModel.calculate(s,t),base=productionModel.calculate(b,8),full=productionModel.calculate(s,8);const parts=[['直接合格',m.firstPass,colors.lime],['返工修复',m.recovered,colors.rework],['最终报废',m.scrapped,colors.loss]];let offset=0;const ring=parts.map(([label,v,color])=>{const pct=m.total?v/m.total:0,arc=`<circle cx="90" cy="90" r="62" pathLength="100" fill="none" stroke="${color}" stroke-width="19" stroke-dasharray="${pct*100} ${100-pct*100}" stroke-dashoffset="${-offset}" transform="rotate(-90 90 90)"/>`;offset+=pct*100;return arc}).join('');$('#composition-chart').innerHTML=`<div class="donut-wrap">${svg(`<circle cx="90" cy="90" r="62" fill="none" stroke="#30465d" stroke-width="19"/>${ring}<text x="90" y="87" text-anchor="middle" class="donut-center">${fmt(m.total)}</text><text x="90" y="107" text-anchor="middle" class="donut-sub">初检总量 · 件</text>`,'0 0 180 180',`累计${t.toFixed(1)}小时，初检${fmt(m.total)}件；${parts.map(p=>p[0]+fmt(p[1])+'件').join('，')}`)}<div class="donut-legend">${parts.map(([name,v,color])=>`<div><i style="background:${color}"></i><span>${name}</span><b>${m.total?fmt(v/m.total*100)+'%':'—'}</b><small>${fmt(v)} 件</small></div>`).join('')}</div></div><p class="viz-readout">${m.total?'合格品 = 直接合格 + 返工修复':'累计时间为 0，尚无产出，构成比例暂不显示。'}</p>`;
 const max=Math.max(200,Math.ceil(Math.max(full.good,base.good)/200)*200),x=h=>55+h/8*390,y=v=>210-v/max*160;
 $('#accumulation-chart').innerHTML=legend('保存的对照','当前方案',colors.lime)+svg(`<text x="55" y="22" class="viz-small">累计合格产出 · 件</text>${[0,max/2,max].map(v=>`<line x1="55" x2="445" y1="${y(v)}" y2="${y(v)}" class="viz-grid"/><text x="45" y="${y(v)+4}" text-anchor="end" class="viz-axis">${fmt(v)}</text>`).join('')}<path d="M55 210L445 ${y(base.good)}" fill="none" stroke="${colors.before}" stroke-width="3" stroke-dasharray="7 5"/><path d="M55 210L445 ${y(full.good)}" fill="none" stroke="${colors.lime}" stroke-width="3"/><line x1="${x(t)}" x2="${x(t)}" y1="40" y2="210" stroke="#a4b7cc" stroke-dasharray="3 5"/><circle cx="${x(t)}" cy="${y(m.good)}" r="6" fill="${colors.lime}"/>${[0,2,4,6,8].map(h=>`<text x="${x(h)}" y="233" text-anchor="middle" class="viz-axis">${h}</text>`).join('')}<text x="250" y="256" text-anchor="middle" class="viz-axis">累计时间 · 小时</text>`,'0 0 485 270',`八小时合格产出，当前方案${fmt(full.good)}件，对照${fmt(base.good)}件`)+`<div class="viz-readout">当前 ${t.toFixed(1)} 小时：${fmt(m.good)} 件 · 对照同期：${fmt(base.goodRate*t)} 件</div>`;
 // Playback redraws should not restart entrance animation every frame.
 $$('.sim-viz-grid .viz-enter').forEach(el=>el.classList.remove('viz-enter'));
}
document.addEventListener('production:update',e=>drawSim(e.detail.state,e.detail.baseline,e.detail.time));
drawSim({speed:100,inspection:80,defect:10,rework:3},{speed:100,inspection:80,defect:10,rework:3},8);
})();
